connect-foundation/2019-09

.github/PULL_REQUEST_TEMPLATE.md, README.md
- README.md 수정(readme-md-generator 사용)
- pull request template 추가
- pull request 양식 자동화
-
=> master로 docs merge

client/package.json, client/src/App.jsx, client/src/presentation/components/index.js, client/src/presentation/components/logo.jsx, client/src/presentation/containers/index.js, client/src/presentation/containers/main-title.jsx, client/src/presentation/pages/index.js, client/src/presentation/pages/main-page.jsx, yarn.lock
- client 부분 logo 컴포넌트
- main title 컨테이너
- main page 스켈레톤 코드
- 역할 구분을 위해 컴포넌트와 컨테이너, 그리고 페이지를 구분함
-
=> develop으로 pair-component-logo merge

client/src/config.js, client/src/presentation/components/Buttons/LargeButton.jsx, client/src/presentation/containers/HowToPlay.jsx, client/src/presentation/containers/Menu.jsx
- PR#172의 변경 요청사항들 을 변경함
- 상수 파일 분리
- 리액트 컴포넌트 프롭스 중 name을 text로 변경
- 유지보수와 안정성을 위해서 변경함
- 상수 변경시 모든 코드에 영향이 없도록 하기 위해
- name 프롭스가 html name과 혼동하지 않도록
=> Pair container menu refactor

server/public/javascripts/index.js, server/socket/index.js, server/socket/utils.js
=> develop으로 pair-webrtc-room-refactor merge

README.md
- 2주차 데모비디오 유튜브 추가
- author정보 추가
=> Docs : README.md 수정

README.md
- try catch의 메인로고를 태그버튼 라인 밑으로 추가
=> Docs: REAMDE.md에 프로젝트 로고 추가

client/package.json, client/public/index.html, client/public/reset.css, client/src/App.jsx, client/src/Root.jsx, client/src/index.js, client/src/presentation/components/Buttons/LargeButton.jsx, client/src/presentation/components/Description.jsx, client/src/presentation/components/QuizDisplay.jsx, client/src/presentation/components/StreamerVideo.jsx, client/src/presentation/components/TextInput.jsx, client/src/presentation/components/Timer.jsx, client/src/presentation/components/UnderlinedLetter.jsx, client/src/presentation/components/UnderlinedSpace.jsx, client/src/presentation/components/index.js, client/src/presentation/containers/Candidates.jsx, client/src/presentation/containers/HowToPlay.jsx, client/src/presentation/containers/MainTitle.jsx, client/src/presentation/containers/Menu.jsx, client/src/presentation/containers/StreamingPanel.jsx, client/src/presentation/containers/index.js, client/src/presentation/pages/Game.jsx, client/src/presentation/pages/MainPage.jsx, client/src/presentation/pages/index.js, yarn.lock
- 기존의 UI에 material UI를 적용
- material UI를 수정하여 react component를 개발
- Route를 만들어 game page를 가도록 구현
- game 페이지의 상단 바와 카운터, 퀴즈파트 구현
- game 페이지의 중앙의 video 컴포넌트 구현
- game 페이지의 출제 문제 선택용 candidate 컴포넌트 구현
- sprint 3의 day 3의 react pair 프로그래밍 코드를 develop으로 머지하여 다른 페어 프로그래밍 팀의 코드와 함치는 작업이 필요함
=> [develop <- pair-react] Sprint 03 Day 03 pull request

server/config.js, server/public/javascripts/index.js, server/socket/index.js, server/socket/utils.js
- 시그널 서버를 통한 sdp/icecandidate 교환
- streamer로 선정된 사람의 video 화면 송출
- 게임 시작시 출제자의 화면을 도전자들에게 보여주기 위함
- 유저의 닉네임 입력후에 서버에서 매칭 시스템 구현 필요
- 채팅 기능 구현 필요
- 서버쪽 게임 시스템 로직 리팩토링 필요
- FE 부분 javascripts viewer와 streamer 이벤트 발생시, 기존의 rtcPeerConnection 초기화 필요
=> develop으로 pair-webrtc-connection merge

server/public/javascripts/config.js, server/public/javascripts/index.js, server/socket/utils.js
- config.js 구조분해 할당으로 import해서 사용
- config에서 사용하는 상수 대문자로 표시
- localStream과 remoteStream을 stream으로 통합
- 생성자에서 init 함수 제거 후 외부 호출
- setLocalStream에서 스트리머 비디오에 스트림 등록
- 서버의 socket/utils.js 안의 currentStreamer 구조분해 할당 사용
- 코드리뷰 사항 적극 반영
-
=> develop으로 pair-webrtc-connection-refactor merge

README.md
- badge의 url typo 수정
- 잘못된 url을 표시하는 것에 대한 수정 필요
=> Docs : badge url 수정

client/public/reset.css, client/src/presentation/components/Buttons/LargeButton.jsx, client/src/presentation/containers/Menu.jsx, client/src/presentation/pages/Game.jsx, client/src/service/socket/config.js, docker-compose.yml, nginx/default.conf.template, server/app.js
- WebRTC로직과 react로 구현한 프론트 결합
- 4 pair로 진행
- 방번호 입력 후 방에 입장
- 입장한 방에서 참가자가 모두 ready 버튼을 누르면 화면 송출 시작
- 가장 먼저 입장한 사람의 화면을 보여줌
- 게임 로직을 추가하기 보다 데모를 위해 정확한
=> [develop <- refactor-for-deploy] 3주차 데모 완료

client/src/service/ClientManager.js, client/src/service/GameManager.js, client/src/service/StreamingManager.js, client/src/service/WebRTCManager.js, client/src/service/config.js
- WebRTCManager 생성
- StreamingManager 생성
- GameManager 생성
- 기능의 분할을 하기 위함
-
=> develop으로 pair-client-refactor merge

client/src/presentation/containers/Menu.jsx, client/src/presentation/containers/PlayerPanel.jsx, client/src/presentation/pages/Game.jsx, client/src/service/ClientManager.js, client/src/service/GameManager.js, client/src/service/StreamingManager.js, client/src/service/WebRTCManager.js, server/config.js, server/socket/handlers/disconnectingHandler.js, server/socket/handlers/index.js, server/socket/handlers/matchHandler.js, server/socket/handlers/sendReadyHandler.js, server/socket/index.js, server/socket/rooms.js
- 게임시작과 영상송출
- 채팅파트와 통합전 collision 체크
- 다시 브랜치
- isStreamer/isViewer -> type으로 변경
- pair programming으로 코드리뷰 생략
=> [develop <- pair-game-system] 영상송출 및 게임시작 부분적완료

client/src/presentation/components/InputWindow.jsx, client/src/presentation/components/MessageInput.jsx, client/src/presentation/containers/ChattingPanel.jsx, client/src/presentation/containers/Menu.jsx, client/src/presentation/pages/Game.jsx, client/src/service/ChattingManager.js, client/src/service/ClientManager.js, client/src/store/globalReducer.js, client/src/store/globalState.js, client/src/utils/constantValues.js, client/src/utils/index.js, server/socket/handlers/index.js, server/socket/handlers/matchHandler.js, server/socket/handlers/sendChattingMessageHandler.js, server/socket/index.js
- 채팅 기능 구현
- 채팅 패널 CSS작업
- 게임 시스템 파트와 통합 전 collision 체크
=> Pair chat system

client/src/service/ClientManager.js, client/src/service/GameManager.js, client/src/service/StreamingManager.js, client/src/utils/index.js, client/src/utils/makeViewPlayerList.js, server/socket/gameController.js, server/socket/handlers/disconnectingHandler.js, server/socket/handlers/index.js, server/socket/handlers/sendReadyHandler.js, server/socket/rooms.js
- 게임이 시작되면 방에 접속할 수 없음
- 게임이 시작되면 레디를 더이상 서버에서 emit하지 않음
- disconnecting 이벤트 발생시 서버와 클라이언트 관련해야 할 로직 부분 구현
페어 프로그래밍을 목적으로 review를 받지 않고 PR
=> [develop <- pair-game-system] chatting system과의 머지를 위한 PR

client/src/presentation/components/ChattingRow.jsx, client/src/presentation/components/ChattingWindow.jsx, client/src/presentation/components/InputWindow.jsx, client/src/presentation/components/Message.jsx, client/src/presentation/components/MessageInput.jsx, client/src/presentation/components/Nickname.jsx, client/src/presentation/components/TextInput.jsx, client/src/presentation/components/Timer.jsx, client/src/presentation/containers/ChattingPanel.jsx, client/src/presentation/containers/Menu.jsx, client/src/presentation/pages/Game.jsx, client/src/service/ChattingManager.js, client/src/service/ClientManager.js, client/src/store/globalReducer.js, client/src/store/globalState.js, client/src/utils/browserLocalStorage.js, client/src/utils/constantValues.js, client/src/utils/index.js, server/socket/handlers/sendChattingMessageHandler.js, server/socket/rooms.js, server/utils/colorGenerator.js
- 채팅방 입장 시 안내 메시지 출력
- 채팅 시 플레이어 닉네임 랜덤색 구현
- 페어 프로그래밍을 목적으로 review를 받지 않고 PR
=> [develop <- pair-chat-system] game system과의 머지를 위한 PR

client/package.json, client/src/config.js, client/src/presentation/components/ChattingRow.jsx, client/src/presentation/components/Description.jsx, client/src/presentation/components/PlayerProfile.jsx, client/src/presentation/components/Slogan.jsx, client/src/presentation/components/index.js, client/src/presentation/containers/Introduction.jsx, client/src/presentation/containers/PlayerPanel.jsx, client/src/presentation/containers/index.js, client/src/presentation/pages/Game.jsx, client/src/presentation/pages/MainPage.jsx, client/src/service/ClientManager.js, client/src/service/GameManager.js, client/src/service/StreamingManager.js, client/src/service/WebRTCManager.js, client/src/store/globalReducer.js, client/src/store/globalState.js, server/socket/gameController.js, server/socket/handlers/disconnectingHandler.js, server/socket/handlers/matchHandler.js, server/socket/handlers/sendReadyHandler.js, server/socket/rooms.js, yarn.lock
- view 작업 브랜치를 pair-game-system으로 merge (conflict 해결)
- 방 이탈에 대한 에러 처리
- webrtc-adpater 적용
- 준비되면 시작되는 게임시스템 적용
- 4 페어프로그래밍으로 코드리뷰 생략
=> Pair game system

client/src/service/ClientManager.js
- 채팅방 퇴장 시 기존 채팅 내용 초기화
- 게임페이지 재입장 시 이전의 채팅 기록이 남아있었음
=> [develop <- feature-reset-chatting] 채팅방 리셋 기능 추가

client/src/presentation/components/StreamerVideo.jsx
- StreamerVideo 컴포넌트에
transform: 'rotateY(180deg)' css style 추가
- 사용자 편의성 고려하여 거울을 보는 것 같이 변경
=> [develop <- feature-video-inversion] merge

client/src/presentation/pages/Game.jsx
=> [develop <- feature-hide-candidates] quiz candidates 안보이게 설정

client/src/service/ClientManager.js
- 방 이탈하여 게임 정지시 레디 풀리 도록 변경
- 4페어로 리뷰 생략
=> Fix : 유저 이탈하고 게임 정지시 ready 풀리도록 변경

client/src/service/ClientManager.js, server/socket/handlers/disconnectingHandler.js
상세 :
- Streamer가 나갈 경우, 다른 플레이어의 isReady가 변경되지 않는 문제 해결
- Viewer가 나가고 게임이 종료될 경우, Streamer의 상태가 변경되지 않는 문제 해결
=> [develop <- fix-player-out-error] 4pair merge

README.md
- readme.md 4주차 데모 추가
- 사용한 기술 내용 추가
=> Docs : 4주차 데모 추가 README.md

client/src/presentation/components/PlayerProfile.jsx, client/src/presentation/containers/PlayerPanel.jsx, client/src/presentation/pages/Game/index.js, client/src/presentation/pages/Game/presenter.jsx, client/src/service/GameManager.js, client/src/store/globalReducer.js, client/src/store/globalState.js
- 이전 Pull Request 코드리뷰 리뷰사항 반영
-  show hide에서 state에 따른 조건부 렌더링으로 변경
- 불필요 주석삭제
- 변수 명칭 컨벤션대로 변경
- 컴포넌트 내부의 불필요한 함수 외부로 이동
=> [develop <- mobile-view] 코드리뷰 사항 반영

client/src/config.js
- client/src/config의 TOP_RANKS 상수 export 제거
=> PR #338 필요사항 반영

client/public/reset.css, client/src/presentation/pages/Game/index.js, client/src/service/ClientManager.js, client/src/service/StreamingManager.js, client/src/service/WebRTCManager.js, server/service/game/GameManager.js
- 폰트 수정
- 카메라 권한 미획득시 메인으로 돌려보내는 기능 추가
- typo 에러 수정
- 게임의 정상적인 진행이 되지 않아 502 에러가 뜨는 상황 발생
- 이후 버그에 관한 브랜치를 따로 생성하여 관리할 예정
- 4인 페어 프로그래밍으로 별도의 리뷰없이 머지
=> [develop <- pair-game-system] merge

server/service/game/eventHandlers/disconnectingHandler.js
- 방에서 레디하고 있는 사람만 남을 경우, 게임 시작 기능 구현
- 게임 시스템 리팩토링측과 이후 merge 하면서 refactor 해야 함
- close #369
=> [demo-bug-fix <- leave-start-bug-fix] merge

client/src/config.js, client/src/presentation/components/TextInput.jsx, client/src/presentation/containers/Menu.jsx
- 닉네임 관련 (길이, 공백) 부분 버그 해결
- 로컬스토리지와 글로벌스테이트 저장 전 확인/처리 후 저장
- 닉네임 설정시 서버로 넘기는 로직은 없으므로 서버쪽 로직은 없는 상태
=> [demo-bug-fix <- nickname-bug-fix] 닉네임 관련 버그 수정

server/service/game/controllers/roomController.js, server/service/game/eventHandlers/disconnectingHandler.js, server/service/game/eventHandlers/sendChattingMessageHandler.js
- 주석 수정 및 불필요한 주석 삭제
- 로직에 상관없는 주석 수정이므로 바로 병합
=> [develop <- fix comment]

.gitignore, docker-compose-dev.yml, docker-compose.yml, server/databaseFiles/databaseModels/seeder/index.js
- 개발용 docker-compose 파일에 mysql에 대한 설정을 추가
- 컨테이너와 호스트의 데이터 volume을 mapping 함으로 컨테이너 삭제시
데이터가 날아가지 않도록 설정함
- gitignore에  mysql/data/ 추가
- path 모듈을 이용하여 path에 영향 받지 않도록 변경
=> [develop <- fix-db-env] DB와 docker를 이용해 로컬 개발가능하게 하는 설정

client/src/constants/events.js, client/src/service/ClientManager.js, client/src/service/GameManager.js, server/service/game/eventHandlers/sendChattingMessageHandler.js
- fe와 be에 updateProfileScore 이벤트를 구현
- sendChattingMessageHandler에서 맞춘 플레이어 정보를 fe로 전송
- fe에서 받은 player 정보를 분석하여 viewPlayerList를 업데이트
- close #408
=> [develop <- profile-score] 점수 변화시 좌측 점수 패널 표시 변경 구현

client/src/presentation/pages/Game/style.js, server/service/game/controllers/gameController.js
- 단어 3개 데이터베이스에서 선정
- 게임 종료시, 플레이어 점수 데이터베이스 저장
- 게임 종료 이벤트가 다수 발생하는 경우가 생기기에, 게임룸에 새로운 상태(ending) 설정,
해당 설정으로 한 게임에 하나의 게임 종료 이벤트만 발생하도록 함
=> [develop <- feature-database-insert-select] 단어 선정, 플레이어 정보 저장

server/service/game/eventHandlers/disconnectingHandler.js, server/service/game/models/GameManager.js
- 4명 중 2 명 이상의 스트리머가 연달아 나갈 경우의 에러 해결
- 3명의 플레이어가 플레이 중 2명이 스트리머를 하고, 나머지 한명이 스트리머인 차례에
해당 스트리머가 나가게 될 경우의 에러 해결
=> [develop <- fix-error-user-leave] 유저가 방을 나갈 경우의 에러 처리

server/service/game/eventHandlers/connectPeerHandler.js, server/service/game/models/GameManager.js
- 스트리머 존재 여부 확인 로직 함수에 추가
- 스트리머 후보 확인에 대한 로직이 이차원 배열에 맞게 변경(flat 사용)
- 게임 중간 나가는 사람들에 대한 예외 처리를 하기 위함
=> [develop <- fix-error-player-leave] 유저가 방을 나갔을 경우에 대한 방어 로직 추가

server/bin/www
- 실제 db 데이터는 host에 저장하고 앞으로 계속 저장해야함
- initiialize를 하면 계속해서 데이터가 쌓임
- 추후 run 환경 분기해서 initialize 처리 여부를 판별할 예정
- 4인 페에로 작업하여 리뷰를 생략함
=> [develop <- remove-ranking-seed] 프로덕션에서 불필요한 initialize 데이터를 제거

client/src/presentation/pages/Game/index.js
- 카메라 권한 허용 에러 수정
- 게임페이지에 접속 후에 카메라 권한이 확인되기전에
init()함수가 호출되고 있었음
=> Fix : 카메라 권한 허용 에러 수정

client/src/hooks/useInnerWidth.js, client/src/hooks/useShiftingToWhichView.js
- 리뷰어님 코드리뷰사항 반영
- useInnerWidth에서 useEffect 정리함수 구현
- useShiftingToWhichView에서 if 문 if else if로 변경
=> [develop <- refactor-custom-hooks ] 리뷰어님 리뷰사항 반영

server/databaseFiles/databaseModels/seeder/scripts/seedQuizzes.js, server/package.json
- initializeQuizzes 함수를 스크립트에서 불러와 dotenv로 환경변수를 적용한 뒤 실행
- server workspace에 seed 명령어로 추가
- 필요한 순간에 seedng 할 수 있도록 (예: docker-compose)
=> [develop <- refactor-db-seeding] DB seed 방식을 명령어 방식에 추가

client/src/presentation/components/QuizDisplay.jsx, server/service/game/controllers/gameController.js, server/service/game/models/GameManager.js
- server의 gameController 부분 리팩토링
- startSet 함수 리팩토링
- endSet 함수 리팩토링
- 이외 필요한 함수들 외부로 내보내는 작업
- 함수의 가독성을 높이기 위한 작업
- quiz를 undefined로 받아도 표시할 수 있도록, client의 components 부분 변경
=> [develop <- refactor-server-game-controller] 서버의 게임 컨트롤러 리팩토링

docker-compose-dev.yml, server/bin/www
- 초기 실행 시 seed 실행 제거
- mysql port 번호 변경
- 로컬 개발용 설정이 병합됨
- 변경된 설정 파일을 병합해서 다시 수정 후 바로 병합
=> [develop <- fix setup config]sequelize 설정 및 dev docker compose 파일 설정

.vscode/settings.json, server/service/game/controllers/gameController.js
- 중복 함수 제거
- emit하는 함수 부분 함수에서 분리
- emit하는 내용을 분리하는 것이 가독성과 로직 분리에 필요한 부분이라 판단
- repeatSet 부분을 ESLint 에러가 발생하지 않게 하려 했지만 이동할 수 없게 코드가 엮여있음
- export 하는 부분에서 endSet 쓰이지 않기에 해당 함수 제거
=> [develop <- refactor-server-game-controller] 서버의 gameController 리팩토링

server/service/game/controllers/gameController.js
- endSet에서 방의 상태 변화 추가(scoreSharing)
- endGame에서 플레이어들의 정답 맞춘 여부 초기화
- eventHandler에서 해당 부분 확인해서 처리하기에 해당 부분 수정
=> [develop <- fix-ingame-error] 게임 정답을 여러번 치거나, 채팅을 하지 못하는 문제 해결

client/src/presentation/components/Buttons/MoreButton.jsx, client/src/presentation/containers/BottomRankPanel.jsx, client/src/presentation/pages/Game/index.js, client/src/presentation/pages/Ranking/index.js
- isBottomVisible 상태를 추가해서 최초 api 요청 후
스켈레톤 컴포넌트를 없앰
- api요청 후 데이터를 받은 뒤 모든 데이터를 가져왔다면
버튼과 loading컴포넌트를 제거하고 api 요청을 막음
=> [develop <- fix ranking rendering bug] Ranking 페이지 데이터 수에 따른 렌더링 버그 수정

client/.eslintrc.json, client/package.json, client/src/__test__/Game.test.js, client/src/presentation/components/Buttons/ExitButton.jsx, client/src/presentation/components/Buttons/MenuButton.jsx, client/src/presentation/components/Buttons/ShareUrlButton.jsx, client/src/presentation/components/ChattingRow.jsx, client/src/presentation/components/ChattingWindow.jsx, client/src/presentation/components/InputWindow.jsx, client/src/presentation/components/MessageInput.jsx, client/src/presentation/components/PlayerProfile.jsx, client/src/presentation/components/RankPodium.jsx, client/src/presentation/components/TextInput.jsx, client/src/presentation/components/Toast.jsx, client/src/presentation/containers/BottomRankPanel.jsx, client/src/presentation/containers/ChattingPanel.jsx, client/src/presentation/containers/PlayerPanel.jsx, client/src/presentation/containers/StreamingPanel/index.js, client/src/presentation/containers/StreamingPanel/presenter.js, client/src/presentation/containers/TopRankPanel.jsx, client/src/presentation/pages/Game/index.js, client/src/presentation/pages/Game/presenter.jsx, client/src/store/globalState.js, yarn.lock
- useRef로 가져온 element가 함수를 가지고 있지않는 라이프사이클중의 상황에 대한  에러 처리
- Prop-types required 올바르게 변경
- 기존 array로 되어있어있는 classes들을 `로 감싸서 넣는 방식으로 변경
- 최상위에만 hook을 사용해야하는 규칙을 알려주고 강제하기 위해 eslint-plugin-react-hooks 설치 Game 페이지 ready 버튼, send 버튼 텍스트 테스트 작성 
- 아래의 컴포넌트들의 prop-types들이 실제로 require 되지 않는 경우에 대한 jest의 경고를 반영함
- InputWindow
- MessageInput
- Toast
- ExitButton
- ChattingPanel
- PlayerPanel
- StreamingPanel
- ChattingRow
- ChattingWindow
- PlayerProfile
- RankPodium
- TextInput
- MenuButton
- ShareUrlButton
- BottomRankPanel
- PlayerPanel
- TopRankPanel
- Game/presenter
#488
=> [develop <- test-game-page ] Game 페이지 컴포넌트 index에 Test 적용 및 그에 따른 warning 수정

docker-compose-dev.yml
- docker-compose-dev.yml에서 nodejs 이미지 파일 삭제
- 개발용 도커를 로컬로 띄우자는 합의를 봤기에 해당 부분 삭제
- 4인 페어로 진행하여 별도의 review 없이 merge
=> Setup : docker-compose의 dev옵션에서 trycatch 제거

client/src/service/GameManager.js
- 세트 종료 메시지 변경
- UI의 가독성이 떨어진다는 의견 반영
=> [develop <- publish-round-set] 세트 종료 메시지 변경

server/__test__/GameManager.test.js, server/package.json
- 생성자
- 플레이어 삽입
- 다음 스트리머 선정
- 스트리머 선택
- 플레이어 나가기
- 스트리머 여부 확인
- 다른 플레이어 반환
해당 함수들에 대한 테스트 코드 작성
- 코드를 변경할 경우에 생기는 변동성 체크를 위한 테스트 코드 추가
- 테스트 코드에 대한 학습 차원의 PR
- 향후 테스트 코드를 다른 파일들에도 적용시킨다면 더 나을 것이라 판단됨
=> [develop <- test-server-game-manager] 서버의 게임매니저 파일 테스트 코드 추가

server/constants/timer.js, server/service/game/models/Timer.js
- ONE_SECOND_BY_MILLISECONDS를 ONE_SECOND_IN_MILLISECONDS로 변경
- BY보다 IN이 보다 정확한 영어 표현
=> [develop <- fix-server-timer-variable] 타이머 변수명 변경

README.md
- 테스트 툴 제거
- 클라이언트에서의 데이터 흐름 표현
=> Docs : 구조 및 데이터흐름 이미지 변경

README.md
=> Docs : 기술스택 이미지 수정

server/service/game/controllers/gameController.js, server/service/game/eventHandlers/disconnectingHandler.js
- repeatSet 함수 분리
- disconnectingHandler switch 적용
- 코드의 가독성을 높이기 위함
- 4인 페어프로그래밍으로 별도의 review 없이 merge
=> [develop <- refactor-repeat-set] repeatSet 함수 분리

client/public/index.html
- apple-touch-icon 태그 제거
- 해당 이미지는 지웠으나 태그가 남아있어서 제거함
- 4인 페어프로그래밍으로 코드 리뷰 생략
=> [develop <- chore ] index.html의 불필요한 link 태그 제거

README.md
- 버전 태그 1.0.0으로 수정
- 7주차 데모 유튜브 비디오 링크 추가
- 4인 페어로 진행하여 별도의 리뷰 비진행
=> [master <- docs] README.md 수정
